// Code generated by MockGen. DO NOT EDIT.
// Source: repository/shop/repository.go

// Package mock_shop_repository is a generated GoMock package.
package mock_shop_repository

import (
	shop "backend-ft/common/shop"
	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/jmoiron/sqlx"
	reflect "reflect"
)

// MockShopRepository is a mock of ShopRepository interface
type MockShopRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShopRepositoryMockRecorder
}

// MockShopRepositoryMockRecorder is the mock recorder for MockShopRepository
type MockShopRepositoryMockRecorder struct {
	mock *MockShopRepository
}

// NewMockShopRepository creates a new mock instance
func NewMockShopRepository(ctrl *gomock.Controller) *MockShopRepository {
	mock := &MockShopRepository{ctrl: ctrl}
	mock.recorder = &MockShopRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockShopRepository) EXPECT() *MockShopRepositoryMockRecorder {
	return m.recorder
}

// GetItemByMultipleSKU mocks base method
func (m *MockShopRepository) GetItemByMultipleSKU(sku []string, tx *sqlx.Tx) ([]shop.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByMultipleSKU", sku, tx)
	ret0, _ := ret[0].([]shop.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByMultipleSKU indicates an expected call of GetItemByMultipleSKU
func (mr *MockShopRepositoryMockRecorder) GetItemByMultipleSKU(sku, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByMultipleSKU", reflect.TypeOf((*MockShopRepository)(nil).GetItemByMultipleSKU), sku, tx)
}

// GetItemBySKU mocks base method
func (m *MockShopRepository) GetItemBySKU(sku string) (*shop.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemBySKU", sku)
	ret0, _ := ret[0].(*shop.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemBySKU indicates an expected call of GetItemBySKU
func (mr *MockShopRepositoryMockRecorder) GetItemBySKU(sku interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemBySKU", reflect.TypeOf((*MockShopRepository)(nil).GetItemBySKU), sku)
}

// InsertCheckout mocks base method
func (m *MockShopRepository) InsertCheckout(userId int64, item shop.Item, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCheckout", userId, item, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCheckout indicates an expected call of InsertCheckout
func (mr *MockShopRepositoryMockRecorder) InsertCheckout(userId, item, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCheckout", reflect.TypeOf((*MockShopRepository)(nil).InsertCheckout), userId, item, tx)
}

// UpdateItemQty mocks base method
func (m *MockShopRepository) UpdateItemQty(items []shop.Item, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemQty", items, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemQty indicates an expected call of UpdateItemQty
func (mr *MockShopRepositoryMockRecorder) UpdateItemQty(items, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemQty", reflect.TypeOf((*MockShopRepository)(nil).UpdateItemQty), items, tx)
}

// GetCartByUserIDAndStatusInCart mocks base method
func (m *MockShopRepository) GetCartByUserIDAndStatusInCart(userID int64) ([]shop.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByUserIDAndStatusInCart", userID)
	ret0, _ := ret[0].([]shop.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByUserIDAndStatusInCart indicates an expected call of GetCartByUserIDAndStatusInCart
func (mr *MockShopRepositoryMockRecorder) GetCartByUserIDAndStatusInCart(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByUserIDAndStatusInCart", reflect.TypeOf((*MockShopRepository)(nil).GetCartByUserIDAndStatusInCart), userID)
}

// GetCartByUserIDAndSKU mocks base method
func (m *MockShopRepository) GetCartByUserIDAndSKU(userID int64, cart shop.Cart, tx *sqlx.Tx) (*shop.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByUserIDAndSKU", userID, cart, tx)
	ret0, _ := ret[0].(*shop.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByUserIDAndSKU indicates an expected call of GetCartByUserIDAndSKU
func (mr *MockShopRepositoryMockRecorder) GetCartByUserIDAndSKU(userID, cart, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByUserIDAndSKU", reflect.TypeOf((*MockShopRepository)(nil).GetCartByUserIDAndSKU), userID, cart, tx)
}

// InsertCart mocks base method
func (m *MockShopRepository) InsertCart(userId int64, cart shop.Cart, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCart", userId, cart, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCart indicates an expected call of InsertCart
func (mr *MockShopRepositoryMockRecorder) InsertCart(userId, cart, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCart", reflect.TypeOf((*MockShopRepository)(nil).InsertCart), userId, cart, tx)
}

// UpdateCart mocks base method
func (m *MockShopRepository) UpdateCart(userId int64, cart shop.Cart, status shop.CartStatus, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCart", userId, cart, status, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCart indicates an expected call of UpdateCart
func (mr *MockShopRepositoryMockRecorder) UpdateCart(userId, cart, status, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCart", reflect.TypeOf((*MockShopRepository)(nil).UpdateCart), userId, cart, status, tx)
}

// UpdateCartStatus mocks base method
func (m *MockShopRepository) UpdateCartStatus(userId int64, sku string, status shop.CartStatus, tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartStatus", userId, sku, status, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCartStatus indicates an expected call of UpdateCartStatus
func (mr *MockShopRepositoryMockRecorder) UpdateCartStatus(userId, sku, status, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartStatus", reflect.TypeOf((*MockShopRepository)(nil).UpdateCartStatus), userId, sku, status, tx)
}
